# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: experimento.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'experimento.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65xperimento.proto\"\x1b\n\x08Mensagem\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"C\n\x0b\x43onfirmacao\x12\x18\n\x10tamanho_recebido\x18\x01 \x01(\x05\x12\x1a\n\x12timestamp_servidor\x18\x02 \x01(\t27\n\x12\x45xperimentoService\x12!\n\x06\x45nviar\x12\t.Mensagem\x1a\x0c.Confirmacaob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimento_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAGEM']._serialized_start=21
  _globals['_MENSAGEM']._serialized_end=48
  _globals['_CONFIRMACAO']._serialized_start=50
  _globals['_CONFIRMACAO']._serialized_end=117
  _globals['_EXPERIMENTOSERVICE']._serialized_start=119
  _globals['_EXPERIMENTOSERVICE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
