# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import jornais_pb2 as jornais__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jornais_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JornalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssinarJornal = channel.unary_stream(
                '/JornalService/AssinarJornal',
                request_serializer=jornais__pb2.AssinaturaRequest.SerializeToString,
                response_deserializer=jornais__pb2.Noticia.FromString,
                _registered_method=True)


class JornalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AssinarJornal(self, request, context):
        """O 'stream' indica que o servidor enviará múltiplas mensagens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JornalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssinarJornal': grpc.unary_stream_rpc_method_handler(
                    servicer.AssinarJornal,
                    request_deserializer=jornais__pb2.AssinaturaRequest.FromString,
                    response_serializer=jornais__pb2.Noticia.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JornalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('JornalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JornalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AssinarJornal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/JornalService/AssinarJornal',
            jornais__pb2.AssinaturaRequest.SerializeToString,
            jornais__pb2.Noticia.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
