# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jornais.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jornais.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rjornais.proto\"9\n\x11\x41ssinaturaRequest\x12\x14\n\x0cnome_cliente\x18\x01 \x01(\t\x12\x0e\n\x06topico\x18\x02 \x01(\t\"N\n\x07Noticia\x12\x0e\n\x06jornal\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t2@\n\rJornalService\x12/\n\rAssinarJornal\x12\x12.AssinaturaRequest\x1a\x08.Noticia0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jornais_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSINATURAREQUEST']._serialized_start=17
  _globals['_ASSINATURAREQUEST']._serialized_end=74
  _globals['_NOTICIA']._serialized_start=76
  _globals['_NOTICIA']._serialized_end=154
  _globals['_JORNALSERVICE']._serialized_start=156
  _globals['_JORNALSERVICE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
